[package]
name = "leptos-node-graph-demo"
version = "0.1.0"
edition = "2024"

[dependencies]
leptos = { version = "0.7", features = ["csr"] }
leptos-node-graph = { path = "../../crates/leptos-node-graph" }
web-sys = { version = "0.3", features = ["console"] }
wasm-bindgen = "0.2"
leptos-use = "0.15"
